Refactor JsonExpressionBuilder.php
yiisoft/db-pgsql pull request #301
Opened 2023-07-25 07:34 UTC by Tigrov

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | -

2023-07-25 07:39 UTC, terabytesoftw commented
Hi, i really don't like the change, why change the interface for the implementation?

2023-07-25 07:47 UTC, Tigrov commented
> Hi, i really don't like the change, why change the interface for the implementation?

It is should be `JsonExpression`
https://github.com/yiisoft/db-pgsql/blob/master/src/Builder/JsonExpressionBuilder.php#L69

And `ExpressionInterface` does not have `getValue()` and `getType()` methods

2023-07-25 08:20 UTC, vjik commented on src/Builder/JsonExpressionBuilder.php
>          $value = $expression->getValue();
`$value` is mixed according to this code: https://github.com/yiisoft/db/blob/master/src/Expression/JsonExpression.php#L32

2023-07-25 08:22 UTC, vjik commented
> Hi, i really don't like the change, why change the interface for the implementation?

This PR not change interface. `ExpressionBuilderInterface` is empty: https://github.com/yiisoft/db/blob/master/src/Expression/ExpressionBuilderInterface.php

2023-07-25 18:29 UTC, terabytesoftw approved these changes

2023-07-26 13:31 UTC, vjik requested changes
Need changelog only.

2023-07-27 14:16 UTC, vjik requested changes

2023-07-27 14:16 UTC, vjik commented on src/Builder/JsonExpressionBuilder.php
> +    private function getTypecast(ExpressionInterface $expression): string
Keep `JsonExpression`. If check `$expression` in `build()` then here will be `JsonExpression` guaranteed.

2023-07-27 14:16 UTC, vjik commented on src/Builder/JsonExpressionBuilder.php
>      public function build(ExpressionInterface $expression, array &$params = []): string
Need check that $expression is instance of `JsonExpression` here.

2023-07-28 08:29 UTC, vjik commented on src/Builder/JsonExpressionBuilder.php
>      public function build(ExpressionInterface $expression, array &$params = []): string
See https://github.com/yiisoft/db-pgsql/pull/300#discussion_r1277069846

2023-07-28 08:30 UTC, vjik commented on CHANGELOG.md
> +- Chg #301: Refactor JsonExpressionBuilder (@Tigrov)
```suggestion
- Enh #301: Refactor `JsonExpressionBuilder` (@Tigrov)
```

2023-07-28 08:31 UTC, vjik approved these changes

2023-07-28 08:52 UTC, merged

2023-07-28 08:52 UTC, vjik commented
@Tigrov Thanks 👍