Support table view constraints
yiisoft/db-pgsql pull request #316
Opened 2023-09-13 10:31 UTC by Tigrov

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #6

2023-11-13 08:44 UTC, vjik requested changes
Looks good, but need add line to changelog

2023-11-14 17:23 UTC, darkdef commented on tests/ColumnSchemaTest.php
> +    public function testPrimaryKeyOfView()
How about add to test  assert:
tableSchema->getPrimaryKey() == ['C_id_1', 'C_id_2';]

2024-01-08 11:37 UTC, darkdef approved these changes

2024-01-08 15:29 UTC, vjik approved these changes

2024-01-09 07:03 UTC, merged